title: Qingsong Liu
position: Postdoctoral Research Associate
affiliation: Manning College of Information and Computer Sciences (CICS), UMass, Amherst 
email: thulqs15@gmail.com
# keywords:  
# google_scholar: https://scholar.google.com/
# github_link: https://github.com/yaoyao-liu/minimal-light
# linkedin: https://www.linkedin.com/
avatar: ./assets/img/personal_image.png
google_analytics: UA-111540567-4
favicon: ./assets/img/MF.jpg
favicon_dark: ./assets/img/MF.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
